// sliced-loop scope plugin for OpenCode.
//
// Confines the frontend, backend and research agents to the directories they
// own. The rules live in scripts/scope.py, shared with every other harness;
// this file only translates OpenCode's tool calls into a question for it, and a
// "no" into a thrown error, which OpenCode hands back to the model.
//
// OpenCode's tool hook does not say which agent is calling, so the agent is
// learned per session: from `chat.message`, which carries it, or else from the
// session record, which the task tool stamps with the subagent's name. A
// headless session started by the loop driver also sets SLICED_LOOP_AGENT.
//
// Generated by scripts/build.py; __SLICED_LOOP_ROOT__ is the plugin checkout.

import { spawnSync } from "node:child_process"
import { readFileSync, statSync } from "node:fs"
import { join } from "node:path"

const SCOPE = "__SLICED_LOOP_ROOT__/scripts/scope.py"

// The confined agents: every source-tree agent named in .sliced-loop.json, plus
// research. Re-read when the file changes, so a newly added agent is covered.
let scoped = { mtime: -1, names: new Set() }
function scopedAgents(directory) {
  const file = join(directory, ".sliced-loop.json")
  let mtime
  try { mtime = statSync(file).mtimeMs } catch { return new Set() }
  if (mtime !== scoped.mtime) {
    let names = []
    try {
      const cfg = JSON.parse(readFileSync(file, "utf8"))
      names = cfg.agents ? Object.keys(cfg.agents) : ["frontend", "backend"]
    } catch {
      names = ["frontend", "backend"]  // unreadable: still confine the classic pair
    }
    scoped = { mtime, names: new Set([...names, "research"]) }
  }
  return scoped.names
}

const READS = new Set(["read", "glob", "grep", "list"])
const WRITES = new Set(["write", "edit", "multiedit", "patch"])

function patchPaths(text) {
  return [...String(text ?? "").matchAll(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/gm)].map((m) => m[1].trim())
}

function check(agent, kind, cwd, { path, command }) {
  const args = [SCOPE, "check", "--agent", agent, "--kind", kind, "--cwd", cwd]
  if (path) args.push("--path", path)
  if (command) args.push("--command", command)
  const r = spawnSync("python3", args, { encoding: "utf8", timeout: 10000 })
  if (r.status === 2) throw new Error(r.stderr.trim() || `Out of scope for the ${agent} agent.`)
  if (r.error || r.status !== 0) {
    // Like a failing hook in the other harnesses: report it, do not wedge the agent.
    console.error(`sliced-loop scope check failed: ${r.error?.message ?? r.stderr}`)
  }
}

export const SlicedLoopScope = async ({ client, directory }) => {
  const agentOf = new Map()

  async function agentFor(sessionID) {
    if (agentOf.has(sessionID)) return agentOf.get(sessionID)
    let agent = ""
    try {
      const res = await client.session.get({ path: { id: sessionID } })
      agent = res?.data?.agent ?? ""
    } catch {
      // Older servers: fall through to the environment.
    }
    agent = agent || process.env.SLICED_LOOP_AGENT || ""
    if (agent) agentOf.set(sessionID, agent)
    return agent
  }

  return {
    "chat.message": async (input) => {
      if (input?.agent) agentOf.set(input.sessionID, input.agent)
    },

    "tool.execute.before": async (input, output) => {
      const agent = await agentFor(input.sessionID)
      if (!scopedAgents(directory).has(agent)) return

      const tool = input.tool
      const a = output?.args ?? {}
      if (READS.has(tool)) return check(agent, "read", directory, { path: a.filePath ?? a.path })
      if (WRITES.has(tool)) return check(agent, "write", directory, { path: a.filePath ?? a.path })
      if (tool === "apply_patch") {
        for (const path of patchPaths(a.patchText ?? a.patch)) check(agent, "write", directory, { path })
        return
      }
      if (tool === "bash") return check(agent, "shell", directory, { command: a.command })
    },
  }
}
