#!/usr/bin/env python3
"""The project's agents: one per source tree, plus the plugin's supervisor and
research agents.

    agents.py list                       every agent, its tree, role and contract
    agents.py add NAME --path DIR --role ui|service
                  [--prefix XX] [--focus TEXT] [--model M] [--create] [--harness H]
                                         a new source tree and the agent that owns it
    agents.py sync [--harness H]         (re)write each tree agent's harness files
    agents.py migrate [--harness H]      move a project from the original two-agent
                                         layout to this one

A tree agent is generated from its role template (src/roles/ui.md or
service.md) with its name, tree, focus and model filled in. In harnesses where
subagents run inside the session — Claude Code, OpenCode, Codex — it has to be
registered as a project agent, so `sync` writes one file per agent:

    claude    .claude/agents/<name>.md
    opencode  .opencode/agents/<name>.md
    codex     .codex/agents/<name>.toml

Gemini CLI and Cursor run tree agents as headless sessions from the same
template (dispatch.py), so they need no files.

Which harnesses a project uses is kept under "harnesses" in .sliced-loop.json;
`--harness` adds one. Generated files point at this plugin by absolute path, so
they are machine-specific: `sync` gitignores them, and the status command says
when they are missing or were generated by another plugin version. Every one is
marked as generated; a file without the mark is never overwritten or removed.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import build  # noqa: E402
import config as cfg_module  # noqa: E402

MARK = "generated by sliced-loop"
IGNORE_HEADER = "# sliced-loop tree agents (generated; machine-specific paths)"


# --- the config file --------------------------------------------------------

def read_raw(root: Path) -> dict:
    path = root / cfg_module.CONFIG_NAME
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except ValueError as exc:
        raise SystemExit(f"{path} is not valid JSON: {exc}")


def write_raw(root: Path, data: dict) -> None:
    (root / cfg_module.CONFIG_NAME).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def to_v2(data: dict) -> dict:
    """The original two-key config, rewritten as an agents map. Idempotent."""
    if "agents" in data:
        return data
    agents = cfg_module.parse_agents(data)
    out = {k: v for k, v in data.items() if k not in ("frontend", "backend")}
    out.setdefault("workspace", cfg_module.DEFAULTS["workspace"])
    out["agents"] = {n: {"path": a["path"], "role": a["role"], "prefix": a["prefix"]}
                     for n, a in agents.items()}
    return out


def parse_model(text: str) -> str | dict:
    """`sonnet` for every harness, or a JSON object with one per harness:
    '{"claude": "sonnet", "opencode": "anthropic/claude-sonnet-5"}'."""
    text = text.strip()
    if not text.startswith("{"):
        return text
    try:
        value = json.loads(text)
    except ValueError as exc:
        raise SystemExit(f"--model looks like JSON but is not valid: {exc}")
    unknown = [h for h in value if h not in build.HARNESSES]
    if unknown or not all(isinstance(v, str) and v for v in value.values()):
        raise SystemExit(f"--model must map harnesses ({', '.join(build.HARNESSES)}) to model names"
                         + (f"; unknown: {', '.join(unknown)}" if unknown else ""))
    return value


def add_harness(data: dict, harness: str | None) -> dict:
    if harness:
        listed = list(data.get("harnesses") or [])
        if harness not in listed:
            data["harnesses"] = listed + [harness]
    return data


# --- workspace scaffolding --------------------------------------------------

def fill(text: str, root: Path, agent: str) -> str:
    return (text.replace("<agent>", agent).replace("<project>", root.name)
            .replace("<date>", date.today().isoformat()))


def scaffold(cfg: dict, name: str) -> list[str]:
    """The agent's memory file, and a contract to publish if it is a service.
    Never overwrites."""
    root, ws, spec = cfg["root"], cfg["workspace_path"], cfg["agents"][name]
    made = []
    memory = ws / "memory" / f"{name}.md"
    if not memory.exists():
        memory.parent.mkdir(parents=True, exist_ok=True)
        memory.write_text(fill((build.PLUGIN_ROOT / "templates" / "memory-agent.md").read_text(), root, name))
        made.append(str(memory.relative_to(root)))
    if spec["role"] == "service":
        contract = ws / "capabilities" / name
        for tpl in sorted((build.PLUGIN_ROOT / "templates" / "capabilities").iterdir()):
            dest = contract / tpl.name
            if not dest.exists():
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(fill(tpl.read_text(), root, name))
                made.append(str(dest.relative_to(root)))
    return made


# --- harness registration ---------------------------------------------------

def registered_harnesses(root: Path) -> list[str]:
    return [h for h in read_raw(root).get("harnesses") or [] if h in build.REGISTERED]


def ignore_generated(root: Path, rels: list[str]) -> None:
    cfg_module.gitignore_add(root, IGNORE_HEADER, [f"/{r}" for r in rels])


def is_generated(path: Path) -> bool:
    try:
        return MARK in path.read_text(encoding="utf-8")[:2000]
    except OSError:
        return False


def sync(cfg: dict, force: bool = False) -> list[str]:
    """Write every tree agent's file for every registered harness; remove
    generated files for agents that no longer exist. Returns what changed."""
    root, changed, written = cfg["root"], [], []
    for h in registered_harnesses(root):
        wanted, notes = {}, {}
        for name, spec in cfg["agents"].items():
            rel, text = build.tree_agent_file(name, spec, h)
            wanted[rel] = text
            model = cfg_module.model_for(spec, h)
            if h == "opencode" and model and "/" not in model:
                notes[rel] = (f"note    {name}: model {model!r} is not an OpenCode provider/model id, "
                              f"so OpenCode uses its default — give one per harness, e.g. "
                              f'"model": {{"claude": "{model}", "opencode": "anthropic/<model>"}}')
        for rel, text in wanted.items():
            dest = root / rel
            if dest.exists() and not is_generated(dest) and not force:
                changed.append(f"SKIPPED {rel} — a hand-written agent has that name (--force replaces it)")
                continue
            written.append(rel)
            if dest.exists() and dest.read_text(encoding="utf-8") == text:
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text, encoding="utf-8")
            changed.append(f"wrote   {rel}")
            if rel in notes:
                changed.append(notes[rel])
        folder = root / Path(next(iter(wanted))).parent if wanted else None
        if folder and folder.is_dir():
            for f in sorted(folder.iterdir()):
                rel = f.relative_to(root).as_posix()
                if rel not in wanted and f.is_file() and is_generated(f):
                    f.unlink()
                    changed.append(f"removed {rel} — no such agent any more")
    ignore_generated(root, written)
    return changed


def stale(cfg: dict) -> list[str]:
    """Why the registered agent files need a sync, if they do."""
    root, why = cfg["root"], []
    for h in registered_harnesses(root):
        for name, spec in cfg["agents"].items():
            rel, text = build.tree_agent_file(name, spec, h)
            dest = root / rel
            if not dest.exists():
                why.append(f"{rel} is missing")
            elif is_generated(dest) and dest.read_text(encoding="utf-8") != text:
                why.append(f"{rel} is out of date")
    return why


# --- commands ---------------------------------------------------------------

def cmd_list(cfg: dict) -> int:
    rows = []
    for name, a in cfg["agents"].items():
        contract = f"{cfg['workspace']}/capabilities/{name}/" if a["role"] == "service" else "—"
        model = a["model"] if isinstance(a["model"], str) else json.dumps(a["model"])
        rows.append((name, a["role"], a["prefix"], f"{a['path']}/", contract, model or "default", a["focus"]))
    widths = [max(len(r[i]) for r in rows + [("agent", "role", "ids", "tree", "contract", "model", "")])
              for i in range(6)]
    head = ("agent", "role", "ids", "tree", "contract", "model")
    print("  ".join(h.ljust(w) for h, w in zip(head, widths)) + "  focus")
    for r in rows:
        print("  ".join(v.ljust(w) for v, w in zip(r[:6], widths)) + f"  {r[6]}")
    print(f"\nplugin agents: supervisor (plans, accepts; reads everything), "
          f"research (answers questions; writes {cfg['workspace']}/research/)")
    print(f"a ui agent consumes contracts; a service publishes its own in capabilities/<name>/. "
          f"Task IDs use the agent's prefix: {', '.join(a['prefix'] + '-001' for a in cfg['agents'].values())}.")
    return 0


def cmd_add(args: argparse.Namespace) -> int:
    root = cfg_module.project_root()
    raw = read_raw(root)
    # A fresh project starts with no agents; an existing one keeps its own.
    data = to_v2(raw) if raw else {"workspace": cfg_module.DEFAULTS["workspace"], "agents": {}}
    agents = data.setdefault("agents", {})
    if args.name in agents:
        raise SystemExit(f"there is already an agent named {args.name!r}")
    entry = {"path": args.path.strip().strip("/"), "role": args.role}
    for key in ("prefix", "focus"):
        if getattr(args, key):
            entry[key] = getattr(args, key)
    if args.model:
        entry["model"] = parse_model(args.model)
    agents[args.name] = entry
    add_harness(data, args.harness)
    cfg_module.parse_agents(data)  # validate names, prefixes and nesting before touching anything

    tree = root / entry["path"]
    if not tree.is_dir():
        if not args.create:
            raise SystemExit(f"{entry['path']}/ does not exist — create it, or pass --create")
        tree.mkdir(parents=True)
        print(f"created   {entry['path']}/")
    write_raw(root, data)
    cfg = cfg_module.load(root)
    spec = cfg["agents"][args.name]
    print(f"added     {args.name}: {spec['role']} agent for {spec['path']}/, task IDs {spec['prefix']}-###"
          + (f", model {args.model}" if args.model else ""))
    for made in scaffold(cfg, args.name):
        print(f"created   {made}")

    import repos
    repos.cmd_init(cfg, split_tracked=False, only=[args.name])
    for line in sync(cfg):
        print(line)
    return 0


def cmd_sync(args: argparse.Namespace) -> int:
    root = cfg_module.project_root()
    data = read_raw(root)
    if not data:
        raise SystemExit(f"no {cfg_module.CONFIG_NAME} here — run the init command first")
    if args.harness and args.harness not in build.HARNESSES:
        raise SystemExit(f"unknown harness {args.harness!r}")
    before = list(data.get("harnesses") or [])
    add_harness(data, args.harness)
    if data.get("harnesses", []) != before:
        write_raw(root, data)
    cfg = cfg_module.load(root)
    for name in cfg["agents"]:
        scaffold(cfg, name)
    changes = sync(cfg, force=args.force)
    if not registered_harnesses(root):
        print("no in-session harness registered (claude, opencode, codex) — nothing to write; "
              "Gemini CLI and Cursor need no agent files")
    print("\n".join(changes) if changes else "agent files are up to date")
    return 0


def cmd_migrate(args: argparse.Namespace) -> int:
    root = cfg_module.project_root()
    raw = read_raw(root)
    if not raw:
        raise SystemExit(f"no {cfg_module.CONFIG_NAME} here — nothing to migrate")
    data = add_harness(to_v2(raw), args.harness)
    if data != raw:
        write_raw(root, data)
        print(f"config    rewrote {cfg_module.CONFIG_NAME} with an \"agents\" map")
    cfg = cfg_module.load(root)

    # The contract used to live directly in capabilities/; each service now has
    # capabilities/<name>/. Only an unambiguous move is made.
    folder = cfg["workspace_path"] / "capabilities"
    loose = [p for p in folder.iterdir() if p.is_file()] if folder.is_dir() else []
    services = [n for n, a in cfg["agents"].items() if a["role"] == "service"]
    if loose and len(services) == 1:
        dest = folder / services[0]
        dest.mkdir(exist_ok=True)
        for p in loose:
            target = dest / p.name
            if target.exists():
                print(f"contract  left {p.name} — {target.relative_to(root)} already exists")
                continue
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", p.name], cwd=folder,
                                     capture_output=True).returncode == 0
            if tracked:
                subprocess.run(["git", "mv", p.name, f"{services[0]}/{p.name}"], cwd=folder, check=True)
            else:
                shutil.move(str(p), target)
            print(f"contract  moved capabilities/{p.name} -> capabilities/{services[0]}/{p.name}")
    elif loose:
        print("contract  capabilities/ has files but not exactly one service — move them into "
              "capabilities/<service>/ by hand")

    for name in cfg["agents"]:
        for made in scaffold(cfg, name):
            print(f"created   {made}")
    for line in sync(cfg):
        print(line)
    if not registered_harnesses(root):
        print("note      no harness recorded — run `agents.py sync --harness <yours>` to register the "
              "tree agents (the plugin no longer ships frontend and backend itself)")
    print("done — commit the changes, and restart the harness so it loads the agents")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    a = sub.add_parser("add")
    a.add_argument("name")
    a.add_argument("--path", required=True, help="the source tree, relative to the project root")
    a.add_argument("--role", required=True, choices=cfg_module.ROLES)
    a.add_argument("--prefix", help="task ID prefix, 2-4 capitals (default: from the name)")
    a.add_argument("--focus", help="what kind of code the tree holds")
    a.add_argument("--model", help="the LLM that runs this agent in the harness")
    a.add_argument("--create", action="store_true", help="create the directory if it does not exist")
    a.add_argument("--harness", choices=list(build.HARNESSES), help="also record this harness")
    s = sub.add_parser("sync")
    s.add_argument("--harness", help="also record this harness")
    s.add_argument("--force", action="store_true", help="replace a hand-written agent with the same name")
    m = sub.add_parser("migrate")
    m.add_argument("--harness", choices=list(build.HARNESSES), help="also record this harness")
    args = parser.parse_args()

    if args.cmd == "list":
        return cmd_list(cfg_module.require())
    return {"add": cmd_add, "sync": cmd_sync, "migrate": cmd_migrate}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
